services:
    # MySQL Database
    mysql:
        image: mysql:8.0
        container_name: blog_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: blog_db
            MYSQL_USER: blog_user
            MYSQL_PASSWORD: blog_password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - blog_network

    # Laravel Backend
    backend:
        build:
            context: .
            dockerfile: backend.Dockerfile
        container_name: blog_backend
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./storage:/var/www/storage
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: blog_db
            DB_USERNAME: blog_user
            DB_PASSWORD: blog_password
        depends_on:
            - mysql
        networks:
            - blog_network

    # Nginx for Laravel
    nginx:
        image: nginx:alpine
        container_name: blog_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx-backend.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend
        networks:
            - blog_network

volumes:
    mysql_data:
        driver: local

networks:
    blog_network:
        driver: bridge